### ISSUE TITLE
Kolorowanie zdjęcia

### ISSUE THREAD

**Issue by ZielonyBuszmen** [MartinWoad/ESKULAP#3]
Znalazłem takie coś na stacku, pomyślałem że może się przydać podczas kolorowania zdjęcia.

Tutaj w przypadku odczytywania informacji o kolorach
https://stackoverflow.com/questions/10593638/how-to-loop-through-all-the-pixels-of-an-image

A tutaj w przypadku tworzenia nowego zdjęcia, pixel po pixelu:
https://stuporglue.org/create-an-image-with-php-pixel-by-pixel/

**Comment by MartinWoad** [comment]
Ponieważ mamy już w sumie kolorowanie zdjęcia w jakiejś sensownej formie, to na razie zamykam.
