### ISSUE TITLE
Brak walidacji w modelu na stronie rejestracji użytkownika

### ISSUE THREAD

**Issue by ZielonyBuszmen** [MartinWoad/ESKULAP#6]
Gdy nie wypełnię wszystkich pól i dodam nowego lekarza, backend wywala błąd. Co prawda, frontend to zablokuje, ale frontend można łatwo zmodyfikować, by przepuścił takie żądanie.

Myślę, że najlepszym rozwiązaniem będzie napisanie odpowiednich Requestów. Co o tym myślicie?

https://laravel.com/docs/5.6/validation#manually-creating-validators

Niżej screen

![obraz](https://user-images.githubusercontent.com/15154575/37567575-1eb8c6a2-2ac9-11e8-9c09-b4665a215b12.png)

**Comment by MartinWoad** [comment]
Trzeba zrobić weryfikację w php przed query.

**Comment by ZielonyBuszmen** [comment]
@MartinWoad Miałeś rację jak o tym wspominałeś na zajęciach 😃 Na bezpieczeństwo musimy też uważać

**Comment by ZielonyBuszmen** [comment]
Ogólnie mogę się tym zająć. Stworzę odpowiedni `request`, który będzie przychodził zamiast standardowego `Request $request` w akcji `zarejestruj` w kontrolerze `AdminController`.

**Comment by ZielonyBuszmen** [comment]
Sorki, niechcący zamknałem issue 😄 Ale już otworzone, wszystko gra! 😛
